"""
Django settings for muxi_shop_api project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#把apps加入到项目根的搜索路径，导入的时候可以直接从源码包导入
sys.path.insert(0,BASE_DIR)
sys.path.insert(0,os.path.join(BASE_DIR,"apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9jal3=*t5n-!8^ns-w9&yw7j9s1g&niy+q!em-x=-wun129zrj"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cart",
    "comment",
    "goods",
    "menu",
    "order",
    "user",
    "address",
    "rest_framework",
    'corsheaders', #解决跨域问题的一个插件
    'agent',
    'pay'
]

CORS_ORIGIN_ALLOW_ALL=True
CORS_ALLOW_CREDENTIALS=True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "muxi_shop_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / 'templates',
        ],
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "muxi_shop_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         #"ENGINE": "django.db.backends.sqlite3",
#         #"NAME": BASE_DIR / "db.sqlite3",
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "muxi_shop",
#         "USER": "admin",
#         "PASSWORD": "123456",
#         "HOST": "192.168.1.119",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
#配置图片文件夹所在路径
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#静态文件服务器配置
#IMAGE_URL='http://localhost:8000/static/product_images/'

#DRF-JWT-TOKEN的全局身份验证配置
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES":["utils.jwt_auth.JwtHeaderAuthentication"]
}

# 支付宝沙箱环境配置
ALIPAY_DEBUG = True  # 使用沙箱环境
APPID = "9021000158614658"

# 回调URL配置（非常重要！）
# 注意：回调URL必须是公网可访问的，如果是本地开发，需要修改以下配置：
# 1. 使用 ngrok 等内网穿透工具获取公网地址
# 2. 或者使用你的服务器公网IP
# 3. 确保端口和路径正确

# 本地开发配置（需要修改为你的实际IP）
LOCAL_IP = "localhost" 
LOCAL_PORT = "8000"  # Django服务端口
FRONTEND_PORT = "8080"  # Vue前端端口

# 异步通知URL（支付宝支付成功后，支付宝服务器会回调这个URL）
APP_NOTIFY_URL = f"http://{LOCAL_IP}:{LOCAL_PORT}/pay/alipay/notify/"

# 同步返回URL（用户在支付宝页面支付成功后，会跳转回这个URL）
RETURN_URL = f"http://{LOCAL_IP}:{LOCAL_PORT}/pay/alipay/return/"

# 前端页面URL（用于跳转回前端）
FRONTEND_SUCCESS_URL = f"http://{LOCAL_IP}:{FRONTEND_PORT}/payment/success"
FRONTEND_FAIL_URL = f"http://{LOCAL_IP}:{FRONTEND_PORT}/payment/fail"



# 支付超时时间（分钟）
PAYMENT_TIMEOUT_MINUTES = 30

# 是否启用模拟支付（当支付宝沙箱不可用时启用）
ENABLE_MOCK_PAYMENT = True

# ======================= 日志配置 =======================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'alipay.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'alipay': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

AGENT_API_URL = 'http://localhost:8001'  # FastAPI服务地址

#做环境区分的代码
CURRENT_ENV = "test"

if CURRENT_ENV == "dev":
    from .settings_dev import *
elif CURRENT_ENV == "test":
    from .settings_test import *
elif CURRENT_ENV == "prod":
    from .settings_prod import *